name: –ó–∞–ø—É—Å–∫ –±–æ—Ç–∞

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'  # –∫–∞–∂–¥—ã–µ 5 —á–∞—Å–æ–≤

jobs:
  run-bot:
    runs-on: windows-latest

    concurrency:
      group: bot-restart
      cancel-in-progress: true

    env:
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: –ö–ª–æ–Ω–∏—Ä–æ–≤–∞—Ç—å —Ä–µ–ø–æ–∑–∏—Ç–æ—Ä–∏–π
        uses: actions/checkout@v3

      - name: –£—Å—Ç–∞–Ω–æ–≤–∏—Ç—å Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: –£—Å—Ç–∞–Ω–æ–≤–∏—Ç—å –∑–∞–≤–∏—Å–∏–º–æ—Å—Ç–∏o
        run: |
          pip install -r requirements.txt

      - name: –ü–æ–¥—Å—Ç–∞–≤–∏—Ç—å —Ç–æ–∫–µ–Ω
        run: |
          (Get-Content config.yml) -replace '^token:.*', "token: `"$env:TOKEN`"" | Set-Content config.yml
          
      - name: –°–¥–µ–ª–∞—Ç—å –¥–≤–∏–∂–æ–∫ –∏—Å–ø–æ–ª–Ω—è–µ–º—ã–º
        run: chmod +x ./engines/lc0.exe

      - name: –ó–∞–ø—É—Å—Ç–∏—Ç—å –±–æ—Ç–∞
        run:  python user_interface.py "matchmaking"
        env: 
          PYTHONUTF8: 1
          
      - name: üîÅ Self-Restart
        if: always()
        run: gh workflow run bot.yml
        env:
          GH_TOKEN: ${{ github.token }}
